<?php
require_once ('articles.theme.inc'); 
function articles_menu() {
    $items = array();
     $items['articles'] = array(
        'title'             =>  'Articles View',  //page title
        'description'       =>  'Articles Information',  //description show when mouse hover on link
        'page callback'     =>  'articles_list',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
     return $items;
}

function articles_list() {
    $query = db_select('countries', 'c');
    $query->fields('c', array('id', 'name'));

    $result = $query->execute();

    $rows = array();
    foreach($result as $res){
        $rows[] = array('id' => $res->id, 'name' => $res->name);
    }
    
    $output = theme('articles_list', array('data'=> $rows)); 
    return $output;
}